server:
  port: 18095

spring:
  batch:
    job:
      name: ${job.name:NONE} #--job.name=yogiyoJob,cpeatsJob
      enabled: false
    jdbc:
      initialize-schema: never

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/RNDB2?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 9597
    tomcat:
      max-active: 50

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  main:
    allow-bean-definition-overriding: true

teams:
  webhook:
    batch:
      url: https://prod2-31.southeastasia.logic.azure.com/workflows/ff3f9add897345aeb6e7d7684fcf1d05/triggers/manual/paths/invoke
